/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sunsethotel.view.rooms;

import br.com.sunsethotel.Util.JPAUtil;
import br.com.sunsethotel.dao.RoomDao;
import br.com.sunsethotel.model.Room;

import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 * @author Henrique
 */
public class NewRoomWindow extends javax.swing.JFrame {

    EntityManager dbConnection;
    private RoomDao roomDao;
    private Integer roomNumber;
    private String roomType;
    private Boolean availableRoom;

    /**
     * Creates new form NewGuestWindow
     */
    public NewRoomWindow() {
        this.dbConnection = JPAUtil.getEntityManager();
        this.roomDao = new RoomDao(dbConnection);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRoomForm = new javax.swing.JPanel();
        roomNumberLabel = new javax.swing.JLabel();
        jtfRoomNumber = new javax.swing.JTextField();
        roomTypeLabel = new javax.swing.JLabel();
        confirmNewRoomButton = new javax.swing.JButton();
        jcbRoomType = new javax.swing.JComboBox<>();
        jcbxRoomAvailable = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New guest");
        setBackground(new java.awt.Color(246, 246, 246));
        setMinimumSize(new java.awt.Dimension(400, 265));
        setName("New guest"); // NOI18N
        setResizable(false);

        addRoomForm.setBackground(new java.awt.Color(246, 246, 246));
        addRoomForm.setMaximumSize(new java.awt.Dimension(400, 265));
        addRoomForm.setMinimumSize(new java.awt.Dimension(400, 265));
        addRoomForm.setPreferredSize(new java.awt.Dimension(400, 265));

        roomNumberLabel.setText("Room number");

        jtfRoomNumber.setToolTipText("Insert guest name");
        jtfRoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRoomNumberActionPerformed(evt);
            }
        });

        roomTypeLabel.setText("Room type");

        confirmNewRoomButton.setText("Confirm");
        confirmNewRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewRoomButtonActionPerformed(evt);
            }
        });

        jcbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single Room Standard", "Double Single Standard", "Couple Room Standard", "Triple Room" }));
        jcbRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRoomTypeActionPerformed(evt);
            }
        });

        jcbxRoomAvailable.setText("Available");
        jcbxRoomAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxRoomAvailableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addRoomFormLayout = new javax.swing.GroupLayout(addRoomForm);
        addRoomForm.setLayout(addRoomFormLayout);
        addRoomFormLayout.setHorizontalGroup(
            addRoomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoomFormLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(addRoomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRoomFormLayout.createSequentialGroup()
                        .addComponent(roomTypeLabel)
                        .addContainerGap(282, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addRoomFormLayout.createSequentialGroup()
                        .addGroup(addRoomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addRoomFormLayout.createSequentialGroup()
                                .addComponent(jcbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbxRoomAvailable))
                            .addComponent(confirmNewRoomButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addRoomFormLayout.createSequentialGroup()
                                .addComponent(roomNumberLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfRoomNumber, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(60, 60, 60))))
        );
        addRoomFormLayout.setVerticalGroup(
            addRoomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRoomFormLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(roomNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roomTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRoomFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxRoomAvailable))
                .addGap(27, 27, 27)
                .addComponent(confirmNewRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addRoomForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addRoomForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRoomNumberActionPerformed
       roomNumber = Integer.valueOf(jtfRoomNumber.getText());
    }//GEN-LAST:event_jtfRoomNumberActionPerformed

    private void confirmNewRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewRoomButtonActionPerformed
        
        
        try {
            Room room = new Room(roomNumber, roomType, availableRoom);
            roomDao.registerRoom(room);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Insert a Room number");
        }
        
        dbConnection.getTransaction().begin();
        dbConnection.getTransaction().commit();
        this.dispose();
    }//GEN-LAST:event_confirmNewRoomButtonActionPerformed

    private void jcbRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRoomTypeActionPerformed
        roomType = jcbRoomType.getSelectedItem().toString();
    }//GEN-LAST:event_jcbRoomTypeActionPerformed

    private void jcbxRoomAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxRoomAvailableActionPerformed
        availableRoom = jcbxRoomAvailable.isSelected();
    }//GEN-LAST:event_jcbxRoomAvailableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewRoomWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewRoomWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewRoomWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewRoomWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewRoomWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addRoomForm;
    private javax.swing.JButton confirmNewRoomButton;
    private javax.swing.JComboBox<String> jcbRoomType;
    private javax.swing.JCheckBox jcbxRoomAvailable;
    private javax.swing.JTextField jtfRoomNumber;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JLabel roomTypeLabel;
    // End of variables declaration//GEN-END:variables
}
