select * from produto;

show processlist;

CREATE TABLE CATEGORIA(ID INT auto_increment, NOME VARCHAR(50) NOT NULL, primary key(ID)) Engine = InnoDB;

INSERT INTO CATEGORIA (NOME) VALUES ('ELETRONICOS');
INSERT INTO CATEGORIA (NOME) VALUES ('ELETRODOMESTICOS');
INSERT INTO CATEGORIA (NOME) VALUES ('MOVEIS');

select * from categoria;

ALTER TABLE PRODUTO ADD COLUMN CATEGORIA_ID INT;

ALTER TABLE PRODUTO ADD foreign key (CATEGORIA_ID) REFERENCES CATEGORIA (ID);

UPDATE PRODUTO SET CATEGORIA_ID = 1;
UPDATE PRODUTO SET CATEGORIA_ID = 3 WHERE ID = 14;